AWSTemplateFormatVersion: 2010-09-09
Description: >-
  shipolog-app

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  apiKey:
    Type: String
    Description: API key for shipstation API
  secret:
    Type: String
    Description: Secret key for shipstation API

Globals:
  Function:
    Runtime: nodejs18.x
    MemorySize: 128
    Timeout: 100
    Architectures:
        - x86_64
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  
  orderWithItemTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub 'OrdersWithItems'

  getOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get-orders.handler
      CodeUri: ./src/api-get-orders
      Timeout: 800
      Environment:
        Variables:
          api_key: !Ref apiKey
          secret: !Ref secret
          ORDER_WITH_ITEM_TABLE_NAME: !Ref orderWithItemTable
      Policies:
         - DynamoDBCrudPolicy:
            TableName: !Ref orderWithItemTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /orders
            Method: GET

  getRatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get-rates.handler
      CodeUri: ./src/api-get-rates
      Environment:
        Variables:
          api_key: !Ref apiKey
          secret: !Ref secret
      Events:
        Api:
          Type: Api
          Properties:
            Path: /rates
            Method: POST

  createLabelFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create-label.handler
      CodeUri: ./src/api-create-label
      Environment:
        Variables:
          api_key: !Ref apiKey
          secret: !Ref secret
          ORDER_WITH_ITEM_TABLE_NAME: !Ref orderWithItemTable
      Policies:
         - DynamoDBCrudPolicy:
            TableName: !Ref orderWithItemTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /label
            Method: POST

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
